Repository alexkim205/G-Desktop-Suite, pull requests merged in 2020-05, with the labels that each got.

#34 Issue 28 undefined about window
  package.json
  src/javascripts/menu.js
Labels: bug

#38 Have window focus persist on switch.
  src/javascripts/childwindow.js
  src/javascripts/mainwindow.js
Labels: bug

#43 Issue 22 window sizing platforms
  src/javascripts/childwindow.js
  src/javascripts/mainwindow.js
Labels: bug

#36 Create homebrew tap for this project
  .vscode/settings.json
  Casks/gsuite.rb
  Casks/update.sh
  README.md
  TODO.md
  package.json
Labels: enhancement

#31 Removes unsupported warning on MacOS
  src/config.js
Labels: bug, help wanted

#59 Refactor config, utils, and theme into helpers folder
  app.js
  src/config.js
  src/css/base.css
  src/css/dark-base.css
  src/css/dark-drive.css
  src/helpers/config.js
  src/helpers/theme.js
  src/helpers/util.js
  src/javascripts/preload-view.js
  src/javascripts/preload.js
  src/js/childwindow.js
  src/js/mainwindow.js
  src/js/menu.js
  src/js/preload-view.js
  src/js/preload.js
  src/stylesheets/dark-docs.js
  src/stylesheets/index.css
  src/templates/index.html
  src/util.js
Labels: code quality

#54 Dark Mode rehaul to use DarkReader and electron-store.
  app.js
  package.json
  src/css/dark-base.css
  src/css/dark-drive.css
  src/helpers/store.js
  src/helpers/theme.js
  src/helpers/util.js
  src/js/childwindow.js
  src/js/mainwindow.js
  src/js/menu.js
  src/js/preload-view.js
  src/js/preload.js
  yarn.lock
Labels: bug

#61 Make store accessible to renderer processes
  app.js
  src/helpers/store.js
  src/js/childwindow.js
Labels: code quality

#68 Integrate eslint and prettier checks in CI.
  .eslintrc
  .jsbeautifyrc
  .prettierrc
  package.json
  src/js/preload-view.js
  src/js/preload.js
  yarn.lock
Labels: code quality, enhancement

#65 Add auto-updating
  .github/workflows/build.yml
  Casks/g-desktop-suite.rb
  README.md
  app.js
  dev-app-update.yml
  package.json
  src/helpers/updater.js
  src/js/mainwindow.js
  src/templates/index.html
  yarn.lock
Labels: enhancement, help wanted

#64 Able to open link in browser based on user preference
  app.js
  src/helpers/store.js
  src/helpers/theme.js
  src/helpers/util.js
  src/js/childwindow.js
  src/js/mainwindow.js
  src/js/menu.js
Labels: enhancement
